# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
 forge_modules:
  stdlib:
   repo: "puppetlabs/stdlib"
   ref: "4.25.1"
  concat:
   repo: "puppetlabs/concat"
   ref: "4.2.1"
  apt:
   repo: "puppetlabs/apt"
   ref: "4.5.1"
  nginx:
   repo: "puppet/nginx"
   ref: "0.12.0"
